{
	$doc_type: 'textarea',
	doc: 'During the past 11 years in business Jazoo has delivered hundreds of thousands of packages. We strive for excellence in communication & service, and will continue to maintain the best possible courier services for each and every client. \n\nWe provide outstanding operations with multiple routes servicing locations on a daily basis. \n\n__Locations Serviced Daily__\n* Calgary \n* Red Deer\n* Edmonton\n* Lloydminster\n* Fort McMurray\n* Whitecourt \n* Fox Creek\n* Grande Prairie\n* Dawson Creek\n* Fort St John\n\n---\n\nJazoo provides daily services to Oil and Gas site locations North of Fort McMurray. All our drivers and fleet trucks are equipped with the proper site access equipment and access badges to match.\n\n__Locations Serviced Daily __\n* Suncor Base Plant\n* Suncor Fort Hills\n* Suncor Firebag\n* Syncrude\n* CNRL Albian\n* Husky Energy\n* Kearl Imperial Oil \n* Civeo (Beaver River Lodge) \n* Clean Harbors (Oil Sands Lodge)\n\nWith drivers situated throughout the province, Jazoo has the ability to respond rapidly and reliably 24 hours a day, 7 days a week, 365 days a year. We have built up a great report with our extensive client list and our reputation is A+. Our clients know that we provide excellent & reliable courier services on a cost effective but competitive price platform. \n\nWe provide Hot Shot services to all Alberta locations and surrounding areas.',
	$abstracted_content_hidden: true,
	abstracted_content: {
		marked_doc: '<p>During the past 11 years in business Jazoo has delivered hundreds of thousands of packages. We strive for excellence in communication &amp; service, and will continue to maintain the best possible courier services for each and every client. </p>\n<p>We provide outstanding operations with multiple routes servicing locations on a daily basis. </p>\n<p><strong>Locations Serviced Daily</strong></p>\n<ul>\n<li>Calgary </li>\n<li>Red Deer</li>\n<li>Edmonton</li>\n<li>Lloydminster</li>\n<li>Fort McMurray</li>\n<li>Whitecourt </li>\n<li>Fox Creek</li>\n<li>Grande Prairie</li>\n<li>Dawson Creek</li>\n<li>Fort St John</li>\n</ul>\n<hr>\n<p>Jazoo provides daily services to Oil and Gas site locations North of Fort McMurray. All our drivers and fleet trucks are equipped with the proper site access equipment and access badges to match.</p>\n<p><strong>Locations Serviced Daily </strong></p>\n<ul>\n<li>Suncor Base Plant</li>\n<li>Suncor Fort Hills</li>\n<li>Suncor Firebag</li>\n<li>Syncrude</li>\n<li>CNRL Albian</li>\n<li>Husky Energy</li>\n<li>Kearl Imperial Oil </li>\n<li>Civeo (Beaver River Lodge) </li>\n<li>Clean Harbors (Oil Sands Lodge)</li>\n</ul>\n<p>With drivers situated throughout the province, Jazoo has the ability to respond rapidly and reliably 24 hours a day, 7 days a week, 365 days a year. We have built up a great report with our extensive client list and our reputation is A+. Our clients know that we provide excellent &amp; reliable courier services on a cost effective but competitive price platform. </p>\n<p>We provide Hot Shot services to all Alberta locations and surrounding areas.</p>\n',
		contents: []
	},
	$contact_types_hidden: true,
	contact_types: {
		contact: {
			name: '',
			phone: '',
			email: ''
		}
	}
}